config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :authors, only: [:index, :show]

  namespace :account do
    resource :settings, only: [:show] do
      member do
        post :make_reader
        post :make_writer
      end
    end
    resource :reader, only: [:show]
    resource :writer, only: [:show] do
      resources :projects, controller: "writers/projects", only: [:index, :show, :new, :create, :edit, :update] do
        resources :compositions, controller: 'writers/projects/compositions', only: [:index, :show, :new, :create, :edit, :update]
      end
    end
  end

  resources :projects, only: [:index, :show] do
    resources :compositions, controller: 'projects/compositions', only: [:index, :show] do
      member do
        post :would_keep_reading
      end
    end
  end

  resources :compositions, only: [:index]

  root to: "home#index"
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true

  mount_uploader :attachment, AttachmentUploader

  delegate :url, :size, :path, to: :attachment

  before_save :update_attachment_attributes

  private

  def update_attachment_attributes
    if attachment.present? && attachment_changed?
      self.original_filename = attachment.file.original_filename
      self.content_type = attachment.file.content_type
    end
  end
end

app/models/avatar.rb
class Avatar < Attachment

end

app/models/composition.rb
class Composition < ActiveRecord::Base
  include Votable
  belongs_to :user
  belongs_to :project, :counter_cache => true
  has_many :votes, as: :votable

  def self.published
    where(published: true)
  end

  def get_title_or_default
    if title.empty?
      "No Title"
    else
      title
    end
  end

  def most_recent_in_project?
    project.most_recently_published_composition == self
  end

  def next
    project.next_composition(self)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :compositions

  def self.published_compositions
    compositions.published
  end

  def my_compositions(user)
    compositions.where(user_id: user.id)
  end

  def collaborative_compositions(user)
    compositions.where.not(user_id: user.id)
  end

  def published_compositions_count
    compositions.where(published: true).count
  end

  def most_recently_published_composition
    compositions.where(published: true).order(updated_at: :asc).last
  end

  def next_composition(composition)
    compositions.where(published: true).where("updated_at > ?", composition.updated_at).first
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true

  before_create :default_start_date

  def self.current
    where("roles.start_date < ? and (roles.end_date is ? or roles.end_date > ?)", Time.now, nil, Time.now)
  end

  def name_as_string
    name || "Role"
  end

  def reader?
    false
  end

  def writer?
    false
  end

  private

  def default_start_date
    self.start_date ||= Time.now
  end
end

app/models/role/reader.rb
class Role::Reader < Role

  def name_as_string
    "Reader"
  end

  def reader?
    true
  end
end

app/models/role/writer.rb
class Role::Writer < Role

  def name_as_string
    "Writer"
  end

  def writer?
    true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
  has_many :compositions
  has_many :roles, dependent: :destroy
  has_many :votes
  has_one :avatar, as: :attachable, autosave: true
  accepts_nested_attributes_for :avatar

  def assign_role(role_type)
    role_type.constantize.create(user: self)
  end

  def cast_vote(vote_type, votable)
    if can_cast_vote_type_on?(vote_type, votable)
      vote = vote_type.constantize.new
      vote.user = self
      vote.votable = votable
      vote.save
    else
      errors.add(:base, "You do not have permission to vote on this!")
      false
    end
  end

  def reader?
    roles.current.where(type: "Role::Reader").any?
  end

  def writer?
    roles.current.where(type: "Role::Writer").any?
  end

  def can_cast_vote_type_on?(vote_type, votable)
    vote_type.constantize.can_be_voted_on_by?(self, votable) && !has_voted_on?(votable)
  end

  def has_voted_on?(votable)
    votes.where(votable: votable).any?
  end
end

app/models/votable.rb
module Votable
  def self.included(base)
    base.has_many :voters, as: :votable, class_name: "Vote", dependent: :destroy
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :votable, polymorphic: true
  belongs_to :user

  def self.votable_classes
    votable_classes_array
  end

  def name_as_string
    name || "Vote"
  end

  def can_be_voted_on_by?(user, votable)
    votable_classes_array.include?(votable.class.name)
  end

  private

  def votable_classes_array
    ["Project", "Composition"]
  end
end

app/models/vote/would_keep_reading.rb
class Vote::WouldKeepReading < Vote

  def self.votable_classes
    ["Composition"]
  end

  def self.can_be_voted_on_by?(user, votable)
    votable_classes.include?(votable.class.name)
  end

  def name_as_string
    name || "Would Keep Reading"
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :authenticate_user!

  layout "account"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index

  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController

  def index
    @compositions = Composition.published
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index

  end

  def show
    @project = Project.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :bio, :email, :password, :password_confirmation, {avatar_attributes: :attachment})
  end

  def account_update_params
    params.require(:user).permit(:username, :bio, :email, :password, :password_confirmation, :current_password, {avatar_attributes: :attachment})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include CompositionHelper
  def markdown(text)
    options = {
      hard_wrap: true,
      filter_html: true,
      autolink: true,
      no_intra_emphasis: true
    }

    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    markdown.render(sanitize text, tags: %w(br blockquote >)).html_safe
  end
end

app/helpers/composition_helper.rb
module CompositionHelper
  def cut_off_at(text, n)
    if n < text.length
      text[0...n] + "...."
    else
      text
    end
  end
end

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "shared/head" %>
</head>
<body>
  <%= render "shared/navigation" %>
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
          <%= render "account/menu" %>
        </div>
        <div class="col-sm-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "shared/head" %>
</head>
<body>
  <%= render "shared/navigation" %>
  <%= yield %>
</body>
</html>

app/views/shared/_head.html.erb
<title>MiniSeriesTester</title>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>

app/views/shared/_navigation.html.erb
<nav class="navbar nav-top">
  <div class="container">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "WritersBloc", root_path %>
      </li>
      <li>
        <%= link_to "Read", compositions_path %>
      </li>
      <li>
        <%= link_to "Write", account_writer_path %>
      </li>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.present? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Profile", account_settings_path %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>