config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :authors, only: [:index, :show]

  namespace :account do
    resource :settings, only: [:show] do
      member do
        post :make_reader
        post :make_writer
      end
    end
    resource :reader, only: [:show]
    resource :writer, only: [:show] do
      resources :projects, controller: "writers/projects", only: [:index, :show, :new, :create, :edit, :update] do
        resources :compositions, controller: 'writers/projects/compositions', only: [:index, :show, :new, :create, :edit, :update]
      end
    end
  end

  resources :projects, only: [:index, :show] do
    resources :compositions, controller: 'projects/compositions', only: [:index, :show] do
      member do
        post :would_keep_reading
      end
    end
  end

  resources :compositions, only: [:index]

  root to: "home#index"
end

app/models/composition.rb
class Composition < ActiveRecord::Base
  include Votable
  belongs_to :user
  belongs_to :project, :counter_cache => true
  has_many :votes, as: :votable

  def self.published
    where(published: true)
  end

  def get_title_or_default
    if title.empty?
      "No Title"
    else
      title
    end
  end

  def most_recent_in_project?
    project.most_recently_published_composition == self
  end

  def next
    project.next_composition(self)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :compositions

  def self.published_compositions
    compositions.published
  end

  def my_compositions(user)
    compositions.where(user_id: user.id)
  end

  def collaborative_compositions(user)
    compositions.where.not(user_id: user.id)
  end

  def published_compositions_count
    compositions.where(published: true).count
  end

  def most_recently_published_composition
    compositions.where(published: true).order(updated_at: :asc).last
  end

  def next_composition(composition)
    compositions.where(published: true).where("updated_at > ?", composition.updated_at).first
  end

end

app/controllers/account/projects/compositions_controller.rb
class Account::Projects::CompositionsController < ApplicationController
  before_action :authorize_project

  def index

  end

  def show
    @composition = @project.compositions.where(id: params[:id]).last
  end

  def edit
    @composition = @project.compositions.where(id: params[:id]).last
  end

  def update
    @composition = @project.compositions.where(id: params[:id]).last
    if @composition.update_attributes(composition_params)
      redirect_to account_project_path(@project)
    else
      render :new
    end
  end

  def new
    @composition = @project.compositions.new
  end

  def create
    @composition = @project.compositions.build(composition_params)
    @composition.user = current_user
    if @composition.save
      redirect_to account_project_path(@project)
    else
      render :new
    end
  end

  private
  def authorize_project
    @project = current_user.projects.where(id: params[:project_id]).last

    if !@project
      redirect_to account_settings_path
    end
  end

  def composition_params
    params.require(:composition).permit(:title, :description, :content, :published)
  end
end

app/controllers/account/projects_controller.rb
class Account::ProjectsController < ApplicationController

  def index

  end

  def show
    @project = current_user.projects.where(id: params[:id]).last
  end

  def edit
    @project = current_user.projects.where(id: params[:id]).last
  end

  def update
    @project = current_user.projects.where(id: params[:id]).last
    if @project.update_attributes(project_params)
      redirect_to account_settings_path
    else
      render :edit
    end
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to account_settings_path
    else
      render :new
    end
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :collaborative)
  end
end

app/controllers/account/writer/projects_controller.rb
class Account::Writer::ProjectsController < AccountController

  def index

  end

  def show
    @project = current_user.projects.where(id: params[:id]).last
  end

  def edit
    @project = current_user.projects.where(id: params[:id]).last
  end

  def update
    @project = current_user.projects.where(id: params[:id]).last
    if @project.update_attributes(project_params)
      redirect_to account_settings_path
    else
      render :edit
    end
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to account_settings_path
    else
      render :new
    end
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :collaborative)
  end
end

app/controllers/account/writer/projetcs/compositions_controller.rb
class Account::Writer::Projects::CompositionsController < AccountController
  before_action :authorize_project

  def index

  end

  def show
    @composition = @project.compositions.where(id: params[:id]).last
  end

  def edit
    @composition = @project.compositions.where(id: params[:id]).last
  end

  def update
    @composition = @project.compositions.where(id: params[:id]).last
    if @composition.update_attributes(composition_params)
      redirect_to account_writer_project_path(@project)
    else
      render :new
    end
  end

  def new
    @composition = @project.compositions.new
  end

  def create
    @composition = @project.compositions.build(composition_params)
    @composition.user = current_user
    if @composition.save
      redirect_to account_writer_project_path(@project)
    else
      render :new
    end
  end

  private
  def authorize_project
    @project = current_user.projects.where(id: params[:project_id]).last

    if !@project
      redirect_to account_settings_path
    end
  end

  def composition_params
    params.require(:composition).permit(:title, :description, :content, :published)
  end
end

app/controllers/account/writers/projects/compositions_controller.rb
class Account::Writers::Projects::CompositionsController < AccountController
  before_action :authorize_project
  before_action :account_navigation

  def index

  end

  def show
    @composition = @project.compositions.where(id: params[:id]).last
  end

  def edit
    @composition = @project.compositions.where(id: params[:id]).last
  end

  def update
    @composition = @project.compositions.where(id: params[:id]).last
    if @composition.update_attributes(composition_params)
      redirect_to account_writer_project_path(@project)
    else
      render :new
    end
  end

  def new
    @composition = @project.compositions.new
  end

  def create
    @composition = @project.compositions.build(composition_params)
    @composition.user = current_user
    if @composition.save
      redirect_to account_writer_project_path(@project)
    else
      render :new
    end
  end

  private
  def authorize_project
    @project = current_user.projects.where(id: params[:project_id]).last

    if !@project
      redirect_to account_settings_path
    end
  end

  def composition_params
    params.require(:composition).permit(:title, :description, :content, :published)
  end

  def account_navigation
    @account_navigation = "writer"
  end
end

app/controllers/account/writers/projects_controller.rb
class Account::Writers::ProjectsController < AccountController
  before_action :account_navigation

  def index

  end

  def show
    @project = current_user.projects.where(id: params[:id]).last
  end

  def edit
    @project = current_user.projects.where(id: params[:id]).last
  end

  def update
    @project = current_user.projects.where(id: params[:id]).last
    if @project.update_attributes(project_params)
      redirect_to account_writer_path
    else
      render :edit
    end
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to account_writer_path
    else
      render :new
    end
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :collaborative)
  end

  def account_navigation
    @account_navigation = "writer"
  end
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController

  def index
    @compositions = Composition.published
  end
end

app/controllers/projects/compositions_controller.rb
class Projects::CompositionsController < ApplicationController
  before_action :project

  def index
    @compositions = @project.published_compositions
  end

  def show
    authorize_composition || return
    redirect_to compositions_path unless @composition.published?
  end

  def would_keep_reading
    authorize_composition || return
    if current_user.cast_vote("Vote::WouldKeepReading", @composition)
      redirect_to project_composition_path(@project, @composition)
    else
      render :show
    end
  end

  private

  def project
    @project = Project.find(params[:project_id])
  end

  def authorize_composition
    @composition = @project.compositions.where(id: params[:id]).last
    if @composition.published?
      true
    else
      redirect_to compositions_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index

  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/composition_helper.rb
module CompositionHelper
  def cut_off_at(text, n)
    if n < text.length
      text[0...n] + "...."
    else
      text
    end
  end
end

app/views/projects/compositions/index.html.erb
<div class="container">
  <% @compositions.each do |composition| %>
    <div class="composition">
      <h4>
        <%= composition.title %>
      </h4>
      <div class="author">
        By <%= link_to composition.user.username, author_path(composition.user) %>
      </div>
      <div class="description">
        <%= composition.description %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/compositions/show.html.erb
<div class="container composition-container">
  <div class="composition">
    <h2>
      <%= @composition.title %>
    </h2>
    <% if @composition.errors.any? %>
      <div class="alert alert-danger">
        <% @composition.errors.each do |error| %>
          <%= error %>
        <% end %>
      </div>
    <% end %>
    <span class="author">
      <i>By</i> <%= link_to @composition.user.username, author_path(@composition.user) %>
    </span>
    <span> | </span>
    <span class="project">
      <i>Part of</i> <%= link_to @composition.project.title, project_path(@composition.project) %>
    </span>
    </div>
    <div class="content">
      <%= markdown(@composition.content) %>
    </div>
    <% if @composition.most_recent_in_project? %>
      <div class="pull-right would-keep-reading">
        <span>
          <% if current_user %>
            <% if current_user.can_cast_vote_type_on?("Vote::WouldKeepReading", @composition) %>
              <%= link_to would_keep_reading_project_composition_path(@project, @composition), method: :post do %>
                <i class="fa fa-glasses" data-toggle="tooltip" title="Let <%= @composition.user.username %> know if you'd keep reading this!"></i>
              <% end %>
            <% elsif current_user.has_voted_on?(@composition) %>
              <i class="fa fa-glasses"></i> <span class="would-keep-reading-message">You would keep reading this!</span>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-glasses" data-toggle="tooltip" title="Let <%= @composition.user.username %> know if you'd keep reading this!"></i>
            <% end %>
          <% end %>
        </span>
      </div>
    <% else %>
      <div class="pull-right continue-reading">
        <%= link_to project_composition_path(@project, @composition.next || @composition) do %>
          Continue Reading <i class="fa fa-caret-right"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>